// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: inventory.sql

package db

import (
	"context"
)

const getAllItems = `-- name: GetAllItems :many
SELECT id, name, product_code, description, categories, binlocation, stock, price, created_at, updated_at FROM inventory
ORDER BY created_at DESC
`

func (q *Queries) GetAllItems(ctx context.Context) ([]Inventory, error) {
	rows, err := q.db.QueryContext(ctx, getAllItems)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Inventory{}
	for rows.Next() {
		var i Inventory
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ProductCode,
			&i.Description,
			&i.Categories,
			&i.Binlocation,
			&i.Stock,
			&i.Price,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
