// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql"
)

type Inventory struct {
	ID        int32        `json:"id"`
	Name      string       `json:"name"`
	Quantity  int32        `json:"quantity"`
	CreatedAt sql.NullTime `json:"created_at"`
	UpdatedAt sql.NullTime `json:"updated_at"`
}
